services:
  - type: web
    name: lartisien-api
    runtime: python
    rootDir: .
    buildCommand: pip install -r api/requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
    plan: free
